# Generated by Django 3.2.18 on 2023-03-07 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todomodel_date_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='date_create',
            new_name='date_created',
        ),
    ]
